#!/usr/bin/env python3
"""Post-build step: emit an Apache .htaccess of real 301s for legacy URLs.

The site is published into UNM's Apache document root for carc.unm.edu, so
unlike GitHub Pages it can issue genuine 301 redirects rather than meta-refresh
stubs. Old Cascade URLs that have been superseded are redirected; old URLs whose
content never moved are deliberately left alone, so the original file keeps
serving at its original address.

Redirects come from two places:

1. OKF provenance — every migrated page records where it came from in
   `sources[].resource`. Recording that is all it takes to get a redirect, so
   the map cannot drift away from the content.
2. migration/redirects-extra.yml — section landings and off-site targets, which
   provenance cannot express.

Run AFTER build_cascade_site.py, alongside postbuild_agent_surface.py.

Usage: python3 scripts/gen_htaccess.py [site_dir]
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
MIGRATION = ROOT / "migration"

LEGACY_HOST_RE = re.compile(r"^https?://carc\.unm\.edu(/.*)$")

# On a static host /index.html IS the site root. A rule for it would fight the
# homepage that build_cascade_site.py installs from web/index.html.
NEVER_REDIRECT = {"/index.html", "/", ""}


def frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n?", text, re.DOTALL)
    if not m:
        return {}
    try:
        data = yaml.safe_load(m.group(1))
    except yaml.YAMLError:
        return {}
    return data if isinstance(data, dict) else {}


def page_url(rel: Path) -> str:
    """Pretty URL for a docs/ page, matching the rest of the build."""
    if rel.name == "index.md":
        parent = str(rel.parent)
        return "/" + (parent + "/" if parent != "." else "")
    return "/" + str(rel.with_suffix("")) + "/"


def from_provenance() -> list[tuple[str, str, str]]:
    """(old_path, new_url, source) for every page recording a carc.unm.edu origin."""
    out = []
    for path in sorted(DOCS.rglob("*.md")):
        rel = path.relative_to(DOCS)
        if rel.parts[0] == "assets":
            continue
        for src in frontmatter(path).get("sources") or []:
            if not isinstance(src, dict):
                continue
            m = LEGACY_HOST_RE.match(str(src.get("resource", "")))
            if m:
                out.append((m.group(1), page_url(rel), f"provenance:{rel}"))
    return out


def from_extra() -> list[tuple[str, str, str]]:
    f = MIGRATION / "redirects-extra.yml"
    if not f.exists():
        return []
    data = yaml.safe_load(f.read_text(encoding="utf-8")) or {}
    out = []
    for entry in data.get("redirects") or []:
        if isinstance(entry, dict) and entry.get("from") and entry.get("to"):
            out.append((str(entry["from"]), str(entry["to"]), "redirects-extra.yml"))
    return out


def quote(path: str) -> str:
    """Apache needs quoting for paths containing spaces."""
    return f'"{path}"' if " " in path else path


def main() -> int:
    site = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "site"
    if not site.is_dir():
        print(f"error: {site} not found — run build_cascade_site.py first", file=sys.stderr)
        return 2

    known = set()
    paths_file = MIGRATION / "legacy-paths.txt"
    if paths_file.exists():
        known = {l for l in paths_file.read_text(encoding="utf-8").splitlines() if l}

    rules: dict[str, tuple[str, str]] = {}
    skipped, unknown = [], []
    for old, new, source in from_provenance() + from_extra():
        if old in NEVER_REDIRECT:
            skipped.append(old)
            continue
        if old in rules and rules[old][0] != new:
            print(f"WARN  {old}: {source} overrides earlier target {rules[old][0]}",
                  file=sys.stderr)
        if known and old not in known:
            unknown.append(f"{old}  ({source})")
        rules[old] = (new, source)

    lines = [
        "# Generated by scripts/gen_htaccess.py — do not edit by hand.",
        "# Legacy Cascade URLs superseded by the rebuilt site. Old URLs whose",
        "# content never moved are intentionally absent: their original files",
        "# remain in the document root and keep serving at their own addresses.",
        "",
    ]

    if (site / "404.html").exists():
        lines += ["ErrorDocument 404 /404.html", ""]
    else:
        print("WARN  no site/404.html — leaving ErrorDocument to the server default",
              file=sys.stderr)

    for old in sorted(rules):
        new, _ = rules[old]
        lines.append(f"Redirect 301 {quote(old)} {quote(new)}")
    lines.append("")

    (site / ".htaccess").write_text("\n".join(lines), encoding="utf-8")

    for u in unknown:
        print(f"WARN  redirect source not in legacy-paths.txt: {u}", file=sys.stderr)
    if skipped:
        print(f"note: refused to redirect site root ({', '.join(sorted(set(skipped)))})")
    print(f"htaccess: {len(rules)} redirect(s)"
          + (f", {len(unknown)} not in the legacy inventory" if unknown else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
